# Generated by Django 4.2 on 2024-07-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_clients_is_active_mailing_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активна'),
        ),
    ]
